[thresholds]
high=100
sleep=20
shutdown=18

[monitor]
poll_seconds=361
grace_seconds=60

[sound]
high_enabled=true
low_enabled=true
high_file=/home/user/Music/snorcon-high-battery-charge-421821.mp3
low_file=/home/user/Music/snorcon-low-battery-charge-421814.mp3
